name: Auto Sign-Off for GitBook Commits

on:
  push:
    branches:
      - master  # change if your default branch is different
      - test

jobs:
  signoff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout master branch explicitly
        run: git checkout master

      - name: Auto Sign-Off GitBook Commits
        run: |
          # set up git config
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # get the last commit message
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Last commit message:"
          echo "$LAST_COMMIT_MESSAGE"
          
          # check if commit message contains "GitBook" (case-insensitive) and lacks a sign-off
          if echo "$LAST_COMMIT_MESSAGE" | grep -iq "gitbook"; then
            if ! echo "$LAST_COMMIT_MESSAGE" | grep -q "Signed-off-by:"; then
              echo "Auto-signing commit..."
              git commit --amend --no-edit -s -S
              git rebase --continue
              git push --force-with-lease
            else
              echo "Commit already contains a Signed-off-by line."
            fi
          else
            echo "Commit message does not contain 'GitBook'. No action taken."
          fi
