name: Auto Sign-Off for GitBook Commits

on:
  push:
    branches:
      - master  # Change if your default branch is different

permissions:
  contents: read

jobs:
  signoff:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Auto Sign-Off GitBook Commits
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if echo "$LAST_COMMIT_MESSAGE" | grep -q "GitBook"; then
            if ! echo "$LAST_COMMIT_MESSAGE" | grep -q "Signed-off-by:"; then
              echo "Auto-signing commit..."
              git commit --amend -m "$LAST_COMMIT_MESSAGE\n\nSigned-off-by: $(git config user.name) <$(git config user.email)>"
              git push --force
            fi
          fi
